android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - .nvm
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
matrix:
  include:
    - stage: Lint
      language: node_js
      os: linux
      node_js: '6'
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: WebPack and Build
      os: osx
      env:
        - WebPackiOS="11"
      osx_image: xcode9.2
      language: node_js
      node_js: '6'
      jdk: oraclejdk8
      before_install:
        - gem install cocoapods
        - pod repo update
      script: >-
        cd demo && npm run build.plugin && npm i && npm run ns-bundle --ios
        --build-app --uglify
    - language: android
      os: linux
      env:
        - WebPackAndroid="26"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script: >-
        cd demo && npm run build.plugin && npm i && npm run ns-bundle --android
        --build-app --uglify --snapshot
    - language: android
      env:
        - BuildAndroid="26"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 6.10.3
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build android
    - os: osx
      env:
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js
      node_js: '6'
      jdk: oraclejdk8
      before_install:
        - gem install cocoapods
        - pod repo update
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build ios
